### ISSUE TITLE
Query 4 Flink runner does not support cogroup by on session window fns

### ISSUE THREAD

**Issue by iemejia** [iemejia/beam#2]
Flink runner breaks on Query4 on Batch mode.
https://github.com/iemejia/beam/blob/BEAM-160-nexmark/integration/java/nexmark/src/main/java/org/apache/beam/integration/nexmark/Query4.java

Stacktrace for reference:
```
        17/02/05 14:01:46 INFO org.apache.beam.runners.flink.translation.FlinkBatchPipelineTranslator: |   |   |   |   visitPrimitiveTransform- 2dc9b0f5GroupByKey
        Exception in thread "main" java.lang.UnsupportedOperationException: Merging WindowFn with windows other than IntervalWindow are not supported.
            at org.apache.beam.runners.flink.translation.FlinkBatchTransformTranslators$GroupByKeyTranslatorBatch.translateNode(FlinkBatchTransformTranslators.java:247)
            at org.apache.beam.runners.flink.translation.FlinkBatchTransformTranslators$GroupByKeyTranslatorBatch.translateNode(FlinkBatchTransformTranslators.java:180)
            at org.apache.beam.runners.flink.translation.FlinkBatchPipelineTranslator.applyBatchTransform(FlinkBatchPipelineTranslator.java:116)
            at org.apache.beam.runners.flink.translation.FlinkBatchPipelineTranslator.visitPrimitiveTransform(FlinkBatchPipelineTranslator.java:100)

        This is in found in org.apache.beam.runners.flink.translation.FlinkBatchTransformTranslators
        
        translateNode(GroupByKey ...)
        translateNode(PerKey ...)
```

**Comment by iemejia** [comment]
For info the current issue in upstream has been officially created:
https://issues.apache.org/jira/browse/BEAM-1772

**Comment by iemejia** [comment]
Fix merged on upstream it works now.
