### ISSUE TITLE
query10: Breaks on Apex Runner (IllegalStateException: Discarded block +  Client does not own the socket any longer)

### ISSUE THREAD

**Issue by iemejia** [iemejia/beam#25]
```
17/03/22 17:28:46 ERROR com.datatorrent.stram.StreamingContainerManager: Unknown container container-10
17/03/22 17:28:46 ERROR com.datatorrent.stram.StreamingContainerManager: Unknown container container-6
17/03/22 17:28:48 ERROR com.datatorrent.netlet.AbstractClientListener: Exception in event loop {id=ProcessWideEventLoop, head=222, tail=222, capacity=1024}
java.lang.IllegalStateException: Discarded block com.datatorrent.bufferserver.internal.DataList$Block@2f38de71{identifier=1.output.1, data=1048576, readingOffset=0, writingOffset=1048576, starting_window=58d2a5fb00000009, ending_window=58d2a5fb0000000a, refCount=1, uniqueIdentifier=18, next=1.output.1, future=java.util.concurrent.FutureTask@14ea55a5} has positive reference count!
	at com.datatorrent.bufferserver.internal.DataList.rewind(DataList.java:121)
	at com.datatorrent.bufferserver.server.Server.handlePublisherRequest(Server.java:338)
	at com.datatorrent.bufferserver.server.Server$UnidentifiedClient.onMessage(Server.java:428)
	at com.datatorrent.netlet.AbstractLengthPrependerClient.read(AbstractLengthPrependerClient.java:149)
	at com.datatorrent.netlet.AbstractClient.read(AbstractClient.java:104)
	at com.datatorrent.netlet.DefaultEventLoop.handleSelectedKey(DefaultEventLoop.java:364)
	at com.datatorrent.netlet.OptimizedEventLoop$SelectedSelectionKeySet.forEach(OptimizedEventLoop.java:59)
	at com.datatorrent.netlet.OptimizedEventLoop.runEventLoop(OptimizedEventLoop.java:192)
	at com.datatorrent.netlet.OptimizedEventLoop.runEventLoop(OptimizedEventLoop.java:157)
	at com.datatorrent.netlet.DefaultEventLoop.run(DefaultEventLoop.java:156)
	at java.lang.Thread.run(Thread.java:745)
17/03/22 17:28:48 ERROR com.datatorrent.netlet.AbstractClientListener: Exception in event loop {id=ProcessWideEventLoop, head=238, tail=238, capacity=1024}
java.nio.channels.CancelledKeyException
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
	at sun.nio.ch.SelectionKeyImpl.interestOps(SelectionKeyImpl.java:82)
	at com.datatorrent.bufferserver.server.Server$UnidentifiedClient.onMessage(Server.java:452)
	at com.datatorrent.netlet.AbstractLengthPrependerClient.read(AbstractLengthPrependerClient.java:149)
	at com.datatorrent.netlet.AbstractClient.read(AbstractClient.java:104)
	at com.datatorrent.netlet.DefaultEventLoop.handleSelectedKey(DefaultEventLoop.java:356)
	at com.datatorrent.netlet.OptimizedEventLoop$SelectedSelectionKeySet.forEach(OptimizedEventLoop.java:59)
	at com.datatorrent.netlet.OptimizedEventLoop.runEventLoop(OptimizedEventLoop.java:192)
	at com.datatorrent.netlet.OptimizedEventLoop.runEventLoop(OptimizedEventLoop.java:157)
	at com.datatorrent.netlet.DefaultEventLoop.run(DefaultEventLoop.java:156)
	at java.lang.Thread.run(Thread.java:745)
17/03/22 17:28:48 ERROR com.datatorrent.stram.engine.StreamingContainer: Operator set [OperatorDeployInfo[id=1,name=Query10.ReadBounded,type=INPUT,checkpoint={ffffffffffffffff, 0, 0},inputs=[],outputs=[OperatorDeployInfo.OutputDeployInfo[portName=output,streamId=stream2,bufferServer=localhost]]]] stopped running due to an exception.
com.datatorrent.netlet.NetletThrowable$NetletRuntimeException: java.lang.UnsupportedOperationException: Client does not own the socket any longer!
	at com.datatorrent.netlet.AbstractClient$1.offer(AbstractClient.java:343)
	at com.datatorrent.netlet.AbstractClient$1.offer(AbstractClient.java:333)
	at com.datatorrent.netlet.AbstractClient.send(AbstractClient.java:279)
	at com.datatorrent.netlet.AbstractLengthPrependerClient.write(AbstractLengthPrependerClient.java:236)
	at com.datatorrent.netlet.AbstractLengthPrependerClient.write(AbstractLengthPrependerClient.java:190)
	at com.datatorrent.stram.stream.BufferServerPublisher.put(BufferServerPublisher.java:139)
	at com.datatorrent.stram.engine.InputNode.run(InputNode.java:177)
	at com.datatorrent.stram.engine.StreamingContainer$2.run(StreamingContainer.java:1407)
Caused by: java.lang.UnsupportedOperationException: Client does not own the socket any longer!
	... 8 more
17/03/22 17:28:50 ERROR com.datatorrent.stram.StreamingContainerManager: Initiating container restart after operator failure PTOperator[id=1,name=Query10.ReadBounded]
17/03/22 17:28:51 ERROR com.datatorrent.stram.StreamingContainerManager: Unknown container container-16
17/03/22 17:28:55 ERROR com.datatorrent.netlet.AbstractLengthPrependerClient: Disconnecting Server.Subscriber{type=stream3/6.input, mask=0, partitions=null} because of an exception.
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at com.datatorrent.netlet.AbstractClient.read(AbstractClient.java:103)
	at com.datatorrent.netlet.DefaultEventLoop.handleSelectedKey(DefaultEventLoop.java:364)
	at com.datatorrent.netlet.OptimizedEventLoop$SelectedSelectionKeySet.forEach(OptimizedEventLoop.java:59)
	at com.datatorrent.netlet.OptimizedEventLoop.runEventLoop(OptimizedEventLoop.java:192)
	at com.datatorrent.netlet.OptimizedEventLoop.runEventLoop(OptimizedEventLoop.java:157)
	at com.datatorrent.netlet.DefaultEventLoop.run(DefaultEventLoop.java:156)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by echauchot** [comment]
Need to qualify and open a ticket if needed

**Comment by echauchot** [comment]
fixed on upstream
