### ISSUE TITLE
query3: fails in streaming mode in direct runner

### ISSUE THREAD

**Issue by echauchot** [iemejia/beam#38]
Exception in thread "main" java.lang.IllegalStateException: **GroupByKey cannot be applied to non-bounded PCollection in the GlobalWindow without a trigger. Use a Window.into or Window.triggering transform prior to GroupByKey.**
	at org.apache.beam.sdk.transforms.GroupByKey.applicableTo(GroupByKey.java:174)
	at org.apache.beam.sdk.transforms.GroupByKey.validate(GroupByKey.java:190)
	at org.apache.beam.sdk.transforms.GroupByKey.validate(GroupByKey.java:121)
	at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:474)
	at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:389)
	at org.apache.beam.sdk.values.PCollection.apply(PCollection.java:154)
	at org.apache.beam.sdk.transforms.join.CoGroupByKey.expand(CoGroupByKey.java:127)
	at org.apache.beam.sdk.transforms.join.CoGroupByKey.expand(CoGroupByKey.java:74)
	at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:475)
	at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:389)
	at org.apache.beam.sdk.transforms.join.KeyedPCollectionTuple.apply(KeyedPCollectionTuple.java:104)
	at org.apache.beam.integration.nexmark.queries.Query3.applyTyped(Query3.java:140)
	at org.apache.beam.integration.nexmark.queries.Query3.applyPrim(Query3.java:161)
	at org.apache.beam.integration.nexmark.NexmarkQuery.expand(NexmarkQuery.java:263)
	at org.apache.beam.integration.nexmark.NexmarkQuery.expand(NexmarkQuery.java:42)
	at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:475)
	at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:389)
	at org.apache.beam.sdk.values.PCollection.apply(PCollection.java:154)
	at org.apache.beam.integration.nexmark.NexmarkRunner.run(NexmarkRunner.java:1212)
	at org.apache.beam.integration.nexmark.NexmarkDriver.runAll(NexmarkDriver.java:69)
	at org.apache.beam.integration.nexmark.drivers.NexmarkSparkDriver.main(NexmarkSparkDriver.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by echauchot** [comment]
fixed groupByKey with trigger but now, null pointer exception on if `(steps.contains(transform.getTransform()))`
`steps` is null

**Comment by iemejia** [comment]
For ref the upstream JIRA
https://issues.apache.org/jira/browse/BEAM-1948

**Comment by echauchot** [comment]
Did a workaround in direct runner (protected from null pointer exception)

**Comment by iemejia** [comment]
Fixed in upstream and by the switch to the Metrics API.
