### ISSUE TITLE
Query 10 breaks on Spark runner, watermark issue in batch mode

### ISSUE THREAD

**Issue by iemejia** [iemejia/beam#4]
Stacktrace for ref:
```
        java.lang.IllegalStateException: Cannot move input watermark time backwards from 2015-07-15T00:00:06.420Z to 2015-07-15T00:00:01.560Z
            at com.google.common.base.Precondixtions.checkState(Preconditions.java:721)
            at org.apache.beam.runners.core.InMemoryTimerInternals.advanceInputWatermark(InMemoryTimerInternals.java:189)
            at org.apache.beam.runners.spark.translation.SparkGroupAlsoByWindowFn.call(SparkGroupAlsoByWindowFn.java:140)
```

**Comment by echauchot** [comment]
Need to qualify and open a ticket if needed

**Comment by echauchot** [comment]
no more breaks
